# NUMPY
IT is a library that handles the multi dimensional array.

In [1]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [3]:
import numpy as np
np. __version__

'1.26.4'

In [4]:
list = [1,2,3,4,5]
print(type(list))

<class 'list'>


In [6]:
arr= np.array(list)
arr

array([1, 2, 3, 4, 5])

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
np.arange(10,30,40,3) # arange can take maximum 3 arguments: (start,stop,step)

TypeError: Cannot interpret '3' as a data type

In [ ]:
np.arange(20,8) # first argument should always be smaller than second argument

array([], dtype=int32)

In [ ]:
np.zeros(3) # result is float datatype

array([0., 0., 0.])

In [15]:
np.zeros((3),dtype= int)

array([0, 0, 0])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5),dtype=int)

array([0, 0, 0, 0, 0])

In [18]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
np.zeros((5,9),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.ones((10,10),dtype=int) # np.ones and np.zeros are only eligible

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])