# numpy

In [3]:
import numpy as np
np.random.rand(3,4)

array([[0.37604531, 0.8141629 , 0.70476037, 0.31811524],
       [0.2839419 , 0.43786084, 0.67515101, 0.75686557],
       [0.14930698, 0.26872099, 0.32456241, 0.2060718 ]])

In [4]:
np.random.rand(2,5)

array([[0.20493276, 0.8393857 , 0.58897356, 0.55035256, 0.6506237 ],
       [0.64861959, 0.91259351, 0.65740387, 0.61065988, 0.03780063]])

In [ ]:
np.random.randint(1,6) # it will print any value between 1 to 6

1

In [14]:
np.random.randint(2,20,5) # it print any five numbers between 2 to 20

array([17,  5, 15, 14, 15])

In [15]:
np.random.randint(10,40,(10,10))

array([[11, 38, 31, 36, 21, 33, 27, 15, 36, 11],
       [37, 25, 11, 27, 25, 19, 13, 25, 27, 14],
       [11, 32, 31, 24, 11, 13, 30, 21, 31, 38],
       [22, 30, 35, 17, 25, 14, 13, 33, 34, 23],
       [20, 17, 13, 34, 21, 36, 13, 39, 34, 18],
       [27, 32, 11, 39, 14, 12, 27, 20, 25, 12],
       [30, 10, 16, 18, 12, 25, 29, 16, 32, 34],
       [15, 29, 16, 25, 34, 39, 29, 39, 12, 33],
       [30, 29, 15, 28, 13, 38, 26, 33, 16, 30],
       [11, 33, 33, 38, 11, 15, 16, 38, 24, 12]])

In [29]:
m1 =np.random.randint(1,20,(10,10)) 
m1  #print numbers between 1 to 20 in 10 * 10 matrix

array([[12,  4,  8, 10, 13, 13, 13,  6,  2, 18],
       [ 1,  2, 13, 15, 12, 16,  9, 18, 19, 13],
       [ 1,  5, 13, 12, 19, 19, 11, 11,  3,  6],
       [14,  4,  3,  2,  6,  4, 12, 13, 11,  3],
       [19,  3, 14, 14, 10,  6, 18,  5, 11, 11],
       [ 4, 18,  6, 12, 11, 10,  4, 17, 18, 12],
       [11, 16,  2,  4,  5, 11, 17,  2, 10, 15],
       [ 7, 19, 15, 19, 11, 14,  3, 19,  6, 17],
       [ 5,  6,  2,  9, 10,  5, 11, 18, 16, 13],
       [ 5,  6,  3, 19,  4,  6,  6, 14, 15, 17]])

In [22]:
l = [0,1,2,3,4,5]
arr=np.array(l)
arr

array([0, 1, 2, 3, 4, 5])

In [23]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [27]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
m1

array([[12,  4,  8, 10, 13, 13, 13,  6,  2, 18],
       [ 1,  2, 13, 15, 12, 16,  9, 18, 19, 13],
       [ 1,  5, 13, 12, 19, 19, 11, 11,  3,  6],
       [14,  4,  3,  2,  6,  4, 12, 13, 11,  3],
       [19,  3, 14, 14, 10,  6, 18,  5, 11, 11],
       [ 4, 18,  6, 12, 11, 10,  4, 17, 18, 12],
       [11, 16,  2,  4,  5, 11, 17,  2, 10, 15],
       [ 7, 19, 15, 19, 11, 14,  3, 19,  6, 17],
       [ 5,  6,  2,  9, 10,  5, 11, 18, 16, 13],
       [ 5,  6,  3, 19,  4,  6,  6, 14, 15, 17]])

In [ ]:
m1.reshape(25,4) # it will reshape the matrix but it should contain same number of elements..25*4=100

array([[12,  4,  8, 10],
       [13, 13, 13,  6],
       [ 2, 18,  1,  2],
       [13, 15, 12, 16],
       [ 9, 18, 19, 13],
       [ 1,  5, 13, 12],
       [19, 19, 11, 11],
       [ 3,  6, 14,  4],
       [ 3,  2,  6,  4],
       [12, 13, 11,  3],
       [19,  3, 14, 14],
       [10,  6, 18,  5],
       [11, 11,  4, 18],
       [ 6, 12, 11, 10],
       [ 4, 17, 18, 12],
       [11, 16,  2,  4],
       [ 5, 11, 17,  2],
       [10, 15,  7, 19],
       [15, 19, 11, 14],
       [ 3, 19,  6, 17],
       [ 5,  6,  2,  9],
       [10,  5, 11, 18],
       [16, 13,  5,  6],
       [ 3, 19,  4,  6],
       [ 6, 14, 15, 17]])

In [34]:
s1=np.random.randint(1,20,(5,5))
s1

array([[ 2,  9, 12, 12,  8],
       [18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9],
       [16, 13, 11, 11, 11],
       [11, 17,  1,  7, 15]])

In [52]:
# SLICING
s1[:]

array([[ 2,  9, 12, 12,  8],
       [18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9],
       [16, 13, 11, 11, 11],
       [11, 17,  1,  7, 15]])

In [37]:
s1[2:3]

array([[ 2,  4,  4, 14,  9]])

In [38]:
s1[3:6]

array([[16, 13, 11, 11, 11],
       [11, 17,  1,  7, 15]])

In [40]:
s1[3:5]

array([[16, 13, 11, 11, 11],
       [11, 17,  1,  7, 15]])

In [41]:
s1[1:4]

array([[18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9],
       [16, 13, 11, 11, 11]])

In [42]:
s1[2:5]

array([[ 2,  4,  4, 14,  9],
       [16, 13, 11, 11, 11],
       [11, 17,  1,  7, 15]])

In [43]:
s1[-1:]

array([[11, 17,  1,  7, 15]])

In [46]:
s1[-4:-1]

array([[18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9],
       [16, 13, 11, 11, 11]])

In [47]:
s1[:-1]

array([[ 2,  9, 12, 12,  8],
       [18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9],
       [16, 13, 11, 11, 11]])

In [49]:
s1

array([[ 2,  9, 12, 12,  8],
       [18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9],
       [16, 13, 11, 11, 11],
       [11, 17,  1,  7, 15]])

In [50]:
s1[1:3]

array([[18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9]])

In [51]:
s1[1:-1]

array([[18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9],
       [16, 13, 11, 11, 11]])

In [53]:
# PRINT SPECIFIC NUMBER

In [54]:
s1

array([[ 2,  9, 12, 12,  8],
       [18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9],
       [16, 13, 11, 11, 11],
       [11, 17,  1,  7, 15]])

In [55]:
s1[1,3]

9

In [56]:
s1[-1,4]

15

In [57]:
s1[-1,-4]

17

In [58]:
s1[-2,-3]

11

In [59]:
s1[-2]

array([16, 13, 11, 11, 11])

In [63]:
s1[:-2]

array([[ 2,  9, 12, 12,  8],
       [18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9]])

In [65]:
s1[::-1]

array([[11, 17,  1,  7, 15],
       [16, 13, 11, 11, 11],
       [ 2,  4,  4, 14,  9],
       [18,  7,  8,  9,  2],
       [ 2,  9, 12, 12,  8]])

In [66]:
s1[::-2]

array([[11, 17,  1,  7, 15],
       [ 2,  4,  4, 14,  9],
       [ 2,  9, 12, 12,  8]])

In [67]:
s1

array([[ 2,  9, 12, 12,  8],
       [18,  7,  8,  9,  2],
       [ 2,  4,  4, 14,  9],
       [16, 13, 11, 11, 11],
       [11, 17,  1,  7, 15]])

In [68]:
s1[1:4:2]

array([[18,  7,  8,  9,  2],
       [16, 13, 11, 11, 11]])

In [69]:
s1.max()

18

In [70]:
s1.min()

1

In [71]:
s1.mean()

9.32

In [72]:
from numpy import*
median(s1)

9.0

In [73]:
m1

array([[12,  4,  8, 10, 13, 13, 13,  6,  2, 18],
       [ 1,  2, 13, 15, 12, 16,  9, 18, 19, 13],
       [ 1,  5, 13, 12, 19, 19, 11, 11,  3,  6],
       [14,  4,  3,  2,  6,  4, 12, 13, 11,  3],
       [19,  3, 14, 14, 10,  6, 18,  5, 11, 11],
       [ 4, 18,  6, 12, 11, 10,  4, 17, 18, 12],
       [11, 16,  2,  4,  5, 11, 17,  2, 10, 15],
       [ 7, 19, 15, 19, 11, 14,  3, 19,  6, 17],
       [ 5,  6,  2,  9, 10,  5, 11, 18, 16, 13],
       [ 5,  6,  3, 19,  4,  6,  6, 14, 15, 17]])

In [74]:
row = 4
col = 5 # variables declared

In [ ]:
m1[1] #specific row

array([ 1,  2, 13, 15, 12, 16,  9, 18, 19, 13])

In [ ]:
m1[:,col] # specific column

array([13, 16, 19,  4,  6, 10, 11, 14,  5,  6])

In [77]:
m1[:,row]

array([13, 12, 19,  6, 10, 11,  5, 11, 10,  4])

In [78]:
m1[::-2]

array([[ 5,  6,  3, 19,  4,  6,  6, 14, 15, 17],
       [ 7, 19, 15, 19, 11, 14,  3, 19,  6, 17],
       [ 4, 18,  6, 12, 11, 10,  4, 17, 18, 12],
       [14,  4,  3,  2,  6,  4, 12, 13, 11,  3],
       [ 1,  2, 13, 15, 12, 16,  9, 18, 19, 13]])

In [79]:
m1

array([[12,  4,  8, 10, 13, 13, 13,  6,  2, 18],
       [ 1,  2, 13, 15, 12, 16,  9, 18, 19, 13],
       [ 1,  5, 13, 12, 19, 19, 11, 11,  3,  6],
       [14,  4,  3,  2,  6,  4, 12, 13, 11,  3],
       [19,  3, 14, 14, 10,  6, 18,  5, 11, 11],
       [ 4, 18,  6, 12, 11, 10,  4, 17, 18, 12],
       [11, 16,  2,  4,  5, 11, 17,  2, 10, 15],
       [ 7, 19, 15, 19, 11, 14,  3, 19,  6, 17],
       [ 5,  6,  2,  9, 10,  5, 11, 18, 16, 13],
       [ 5,  6,  3, 19,  4,  6,  6, 14, 15, 17]])

In [82]:
m1[2:3,4:7]

array([[19, 19, 11]])

In [83]:
m1[2:6,2:4]

array([[13, 12],
       [ 3,  2],
       [14, 14],
       [ 6, 12]])

In [84]:
m1[2:3,2:3]

array([[13]])

In [85]:
m1[3:5,2:4]

array([[ 3,  2],
       [14, 14]])

# MASKING

In [86]:
m1

array([[12,  4,  8, 10, 13, 13, 13,  6,  2, 18],
       [ 1,  2, 13, 15, 12, 16,  9, 18, 19, 13],
       [ 1,  5, 13, 12, 19, 19, 11, 11,  3,  6],
       [14,  4,  3,  2,  6,  4, 12, 13, 11,  3],
       [19,  3, 14, 14, 10,  6, 18,  5, 11, 11],
       [ 4, 18,  6, 12, 11, 10,  4, 17, 18, 12],
       [11, 16,  2,  4,  5, 11, 17,  2, 10, 15],
       [ 7, 19, 15, 19, 11, 14,  3, 19,  6, 17],
       [ 5,  6,  2,  9, 10,  5, 11, 18, 16, 13],
       [ 5,  6,  3, 19,  4,  6,  6, 14, 15, 17]])

In [87]:
m1[m1>10]

array([12, 13, 13, 13, 18, 13, 15, 12, 16, 18, 19, 13, 13, 12, 19, 19, 11,
       11, 14, 12, 13, 11, 19, 14, 14, 18, 11, 11, 18, 12, 11, 17, 18, 12,
       11, 16, 11, 17, 15, 19, 15, 19, 11, 14, 19, 17, 11, 18, 16, 13, 19,
       14, 15, 17])

In [88]:
m1[m1>=10]

array([12, 10, 13, 13, 13, 18, 13, 15, 12, 16, 18, 19, 13, 13, 12, 19, 19,
       11, 11, 14, 12, 13, 11, 19, 14, 14, 10, 18, 11, 11, 18, 12, 11, 10,
       17, 18, 12, 11, 16, 11, 17, 10, 15, 19, 15, 19, 11, 14, 19, 17, 10,
       11, 18, 16, 13, 19, 14, 15, 17])

In [89]:
m1[m1<=5]

array([4, 2, 1, 2, 1, 5, 3, 4, 3, 2, 4, 3, 3, 5, 4, 4, 2, 4, 5, 2, 3, 5,
       2, 5, 5, 3, 4])

In [90]:
m1[m1!=15]

array([12,  4,  8, 10, 13, 13, 13,  6,  2, 18,  1,  2, 13, 12, 16,  9, 18,
       19, 13,  1,  5, 13, 12, 19, 19, 11, 11,  3,  6, 14,  4,  3,  2,  6,
        4, 12, 13, 11,  3, 19,  3, 14, 14, 10,  6, 18,  5, 11, 11,  4, 18,
        6, 12, 11, 10,  4, 17, 18, 12, 11, 16,  2,  4,  5, 11, 17,  2, 10,
        7, 19, 19, 11, 14,  3, 19,  6, 17,  5,  6,  2,  9, 10,  5, 11, 18,
       16, 13,  5,  6,  3, 19,  4,  6,  6, 14, 17])

# PROGRAM TO GENERATE OTP

In [95]:
import numpy as np
otp = np.random.randint(0,6,4)
print(f"YOUR OTP IS {otp} . Please don't share with anyone")

YOUR OTP IS [3 4 2 0] . Please don't share with anyone
